name: Luege
options:
  bundleIdPrefix: com.luege
  deploymentTarget:
    tvOS: "17.0"
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

packages:
  AMSMB2:
    url: https://github.com/amosavian/AMSMB2.git
    from: "4.0.0"
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    from: "1.15.0"

targets:
  Luege tvOS:
    type: application
    platform: tvOS
    sources:
      - path: Shared
        createIntermediateGroups: true
      - path: tvOS
        createIntermediateGroups: true
    dependencies:
      - package: AMSMB2
        embed: true
      # VLCKit is provided via CocoaPods (see Podfile)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.luege.app
        INFOPLIST_FILE: tvOS/Info.plist
        PRODUCT_NAME: Luege
        ASSETCATALOG_COMPILER_APPICON_NAME: App Icon & Top Shelf Image
        DEVELOPMENT_TEAM: 7C48W538SL
        CODE_SIGN_STYLE: Automatic

  Luege iOS:
    type: application
    platform: iOS
    sources:
      - path: Shared
        createIntermediateGroups: true
      - path: iOS
        createIntermediateGroups: true
    dependencies:
      - package: AMSMB2
        embed: true
      # VLCKit is provided via CocoaPods (see Podfile)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.luege.app
        INFOPLIST_FILE: iOS/Info.plist
        PRODUCT_NAME: Luege
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        DEVELOPMENT_TEAM: 7C48W538SL
        CODE_SIGN_STYLE: Automatic
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO

  LuegeScreenshotTests iOS:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LuegeScreenshotTests
        createIntermediateGroups: true
        excludes:
          - "**/__Snapshots__/**"
    dependencies:
      - target: Luege iOS
      - package: SnapshotTesting
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.luege.screenshottests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Luege.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Luege"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: YES

  LuegeScreenshotTests tvOS:
    type: bundle.unit-test
    platform: tvOS
    sources:
      - path: LuegeScreenshotTests
        createIntermediateGroups: true
        excludes:
          - "**/__Snapshots__/**"
    dependencies:
      - target: Luege tvOS
      - package: SnapshotTesting
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.luege.screenshottests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Luege.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Luege"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: YES

  LuegeCoreTests iOS:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LuegeCoreTests
        createIntermediateGroups: true
    dependencies:
      - target: Luege iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.luege.coretests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Luege.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Luege"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: YES

  LuegeCoreTests tvOS:
    type: bundle.unit-test
    platform: tvOS
    sources:
      - path: LuegeCoreTests
        createIntermediateGroups: true
    dependencies:
      - target: Luege tvOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.luege.coretests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Luege.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Luege"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: YES

  LuegeIntegrationTests iOS:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LuegeIntegrationTests
        createIntermediateGroups: true
    dependencies:
      - target: Luege iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.luege.integrationtests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Luege.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Luege"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: YES

  LuegeIntegrationTests tvOS:
    type: bundle.unit-test
    platform: tvOS
    sources:
      - path: LuegeIntegrationTests
        createIntermediateGroups: true
    dependencies:
      - target: Luege tvOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.luege.integrationtests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Luege.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Luege"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: YES

schemes:
  Luege iOS:
    build:
      targets:
        Luege iOS: all
    run:
      config: Debug
    archive:
      config: Release

  Luege tvOS:
    build:
      targets:
        Luege tvOS: all
    run:
      config: Debug
    archive:
      config: Release

  LuegeScreenshotTests iOS:
    build:
      targets:
        Luege iOS: all
        LuegeScreenshotTests iOS: [test]
    test:
      gatherCoverageData: false
      targets:
        - name: LuegeScreenshotTests iOS
          parallelizable: false
          randomExecutionOrder: false

  LuegeScreenshotTests tvOS:
    build:
      targets:
        Luege tvOS: all
        LuegeScreenshotTests tvOS: [test]
    test:
      gatherCoverageData: false
      targets:
        - name: LuegeScreenshotTests tvOS
          parallelizable: false
          randomExecutionOrder: false

  LuegeCoreTests iOS:
    build:
      targets:
        Luege iOS: all
        LuegeCoreTests iOS: [test]
    test:
      gatherCoverageData: false
      targets:
        - name: LuegeCoreTests iOS
          parallelizable: true
          randomExecutionOrder: true

  LuegeCoreTests tvOS:
    build:
      targets:
        Luege tvOS: all
        LuegeCoreTests tvOS: [test]
    test:
      gatherCoverageData: false
      targets:
        - name: LuegeCoreTests tvOS
          parallelizable: true
          randomExecutionOrder: true

  LuegeIntegrationTests iOS:
    build:
      targets:
        Luege iOS: all
        LuegeIntegrationTests iOS: [test]
    test:
      gatherCoverageData: false
      targets:
        - name: LuegeIntegrationTests iOS
          parallelizable: false
          randomExecutionOrder: false

  LuegeIntegrationTests tvOS:
    build:
      targets:
        Luege tvOS: all
        LuegeIntegrationTests tvOS: [test]
    test:
      gatherCoverageData: false
      targets:
        - name: LuegeIntegrationTests tvOS
          parallelizable: false
          randomExecutionOrder: false
